language: php

jobs:
  include:
    - php: 8.4
      dist: noble
    
before_script:
  - phpenv config-add test/resources/php.ini

install:
  - composer install --no-interaction --prefer-dist

script:
  - composer test
